### ISSUE TITLE
Netlogon events aren't loading text

### ISSUE THREAD

**Issue by chrismcgurk** [bill-long/EventLogExpert#86]
Looks like all event IDs for Netlogon events in a System log are not loading text - so far I've seen 5783, 5816, 5719, 5823, 5817 loading with text "The description for this event could not be found. The following information was included with the event" - this source is Windows 2012 R2 Standard

**Comment by bill-long** [comment]
This is due to case-sensitivity. The provider name in the provider metadata is "Netlogon", but the name in the evtx file is "NETLOGON". I switched to the Dixie.js library which can do a case-insensitive search, but this made performance terrible. Instead we're going to force all provider names to uppercase when storing and searching. We're going to keep Dixie.js though, because it greatly simplified the database code (we just won't use it to do equalsIgnoreCase).
